<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ros2_fra2mo)/urdf/utility_macro.xacro" />

  <xacro:macro name="fra2mo_base" params="prefix">

    <xacro:property name="base_height" value="0.180" /> 
    <xacro:property name="base_radius" value="0.11" /> 
    <xacro:property name="base_mass" value="5" />
    <xacro:property name="wheel_mass" value="2.5" />
    <xacro:property name="wheel_radius" value="0.035" /> 
    <xacro:property name="wheel_axle" value="0.124" /> 

    <link name="${prefix}base_footprint"/>

    <link name="${prefix}base_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${base_mass}" />
        <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
      </inertial>
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_body.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Blue" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision>
        <geometry> <cylinder length="${base_height}" radius="${base_radius}" /> </geometry>
        <origin xyz="0 0.0 ${(base_height/2.0)-0.05}" rpy="0 0 0" />
      </collision> 
      <collision>
        <geometry> <sphere radius="0.019" /> </geometry>
        <origin xyz="-0.0825 0.0 -0.04" rpy="0 0 0" />
      </collision>       
    </link>

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <parent link="${prefix}base_footprint" />
      <child link="${prefix}base_link" />
      <origin xyz="0.0 0.0 0.059" rpy="0 0 0" />
    </joint>

    <link name="${prefix}left_wheel_link">
      <visual> 
        <geometry> <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" /> </geometry>
        <material name="Black" />
      </visual>
      <collision> 
        <geometry> <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" /> </geometry>
      </collision>
      <inertial> <origin xyz="0 0 0" /> <mass value="${wheel_mass}" /> <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" /> </inertial>
    </link>

    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}left_wheel_link" />
      <origin xyz="0.04025 0.062 -0.024" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="800" velocity="100" /> <dynamics damping="0.5" friction="0.01" />
    </joint>

    <link name="${prefix}right_wheel_link">
      <visual> 
        <geometry> <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" /> </geometry>
        <material name="Black"/>
      </visual>
      <collision> 
        <geometry> <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" /> </geometry>
      </collision>
      <inertial> <origin xyz="0 0 0" /> <mass value="${wheel_mass}" /> <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" /> </inertial>
    </link>

    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}right_wheel_link" />
      <origin xyz="0.04025 -0.062 -0.024" rpy="0 0 ${-M_PI}" />
      <axis xyz="0 -1 0" />
      <limit effort="800" velocity="100" /> <dynamics damping="0.5" friction="0.01" />
    </joint>

    <link name="${prefix}d435_link">
      <visual> <geometry> <box size="0.02 0.05 0.02"/> </geometry> <material name="Red"/> </visual>
    </link>
    <link name="${prefix}lidar_link" />

    <joint name="${prefix}d435_joint" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}d435_link" />
      <origin xyz="0.10 0.0 0.075" rpy="0 0 0" /> 
    </joint>

    <joint name="${prefix}lidar_joint" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}lidar_link" />
      <origin xyz="0.0 0.0 0.125" rpy="0 0 0" />
    </joint>

    <link name="${prefix}trailer_link">
      <visual>
        <origin xyz="-0.4 0 0" rpy="0 0 0" />
        <geometry> <box size="0.3 0.25 0.05"/> </geometry> 
        <material name="Grey"> <color rgba="0.5 0.5 0.5 1"/> </material>
      </visual>
      <collision> 
        <origin xyz="-0.4 0 0" rpy="0 0 0" />
        <geometry> <box size="0.3 0.25 0.05"/> </geometry> 
      </collision>
      <visual>
        <origin xyz="-0.2 0 0" rpy="0 1.57 0" /> 
        <geometry> <cylinder radius="0.01" length="0.4"/> </geometry> 
        <material name="Black"/>
      </visual>
      <inertial> 
        <origin xyz="-0.3 0 0" /> 
        <mass value="2.0"/> 
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/> 
      </inertial>
    </link>

    <joint name="${prefix}trailer_hitch_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}trailer_link" />
      <origin xyz="-0.12 0.0 -0.02" rpy="0 0 0" /> 
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix}trailer_wheel_l">
      <visual> <geometry> <cylinder radius="0.035" length="0.02"/> </geometry> <material name="Black"/> </visual>
      <collision> <geometry> <cylinder radius="0.035" length="0.02"/> </geometry> </collision>
      <inertial> <mass value="0.01"/> <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/> </inertial>
    </link>

    <joint name="${prefix}trailer_wheel_l_joint" type="continuous">
      <parent link="${prefix}trailer_link" />
      <child link="${prefix}trailer_wheel_l" />
      <origin xyz="-0.4 0.14 -0.02" rpy="1.57 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix}trailer_wheel_r">
      <visual> <geometry> <cylinder radius="0.035" length="0.02"/> </geometry> <material name="Black"/> </visual>
      <collision> <geometry> <cylinder radius="0.035" length="0.02"/> </geometry> </collision>
      <inertial> <mass value="0.01"/> <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/> </inertial>
    </link>

    <joint name="${prefix}trailer_wheel_r_joint" type="continuous">
      <parent link="${prefix}trailer_link" />
      <child link="${prefix}trailer_wheel_r" />
      <origin xyz="-0.4 -0.14 -0.02" rpy="1.57 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix}parcel_link">
      <visual>
        <geometry> <box size="0.2 0.2 0.2"/> </geometry>
        <material name="Brown"> <color rgba="0.6 0.4 0.2 1"/> </material>
      </visual>
      <collision> <geometry> <box size="0.2 0.2 0.2"/> </geometry> </collision>
      <inertial> <mass value="0.0001"/> <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/> </inertial>
    </link>

    <joint name="${prefix}trailer_to_parcel" type="fixed">
      <parent link="${prefix}trailer_link"/>
      <child link="${prefix}parcel_link"/>
      <origin xyz="-0.4 0 0.125" rpy="0 0 0"/> 
    </joint>

    <link name="${prefix}fra2mo_tag_link">
      <visual> 
        <geometry> <box size="0.1 0.1 0.001"/> </geometry> 
        <material name="White"> <color rgba="1 1 1 1"/> </material> 
      </visual>
      <inertial> <mass value="0.00001"/> <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/> </inertial>
    </link>

    <joint name="${prefix}parcel_to_fra2mo_tag" type="fixed">
      <parent link="${prefix}parcel_link"/>
      <child link="${prefix}fra2mo_tag_link"/>
      <origin xyz="0 0 0.101" rpy="0 0 0"/> 
    </joint>

    <gazebo reference="${prefix}fra2mo_tag_link">
      <visual>
        <material>
          <diffuse>1 1 1 1</diffuse>
          <specular>0 0 0 1</specular>
          <pbr>
            <metal>
              <albedo_map>file://$(find ros2_fra2mo)/models/arucotag_201/aruco-201.png</albedo_map>
            </metal>
          </pbr>
        </material>
      </visual>
    </gazebo>

    <link name="${prefix}tag_left_link">
      <visual> 
        <geometry> <box size="0.1 0.1 0.001"/> </geometry> 
        <material name="White"> <color rgba="1 1 1 1"/> </material> 
      </visual>
      <inertial> <mass value="0.00001"/> <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/> </inertial>
    </link>

    <joint name="${prefix}parcel_to_tag_left" type="fixed">
      <parent link="${prefix}parcel_link"/>
      <child link="${prefix}tag_left_link"/>
      <origin xyz="0 0.101 0" rpy="-1.5708 0 0"/> 
    </joint>

    <gazebo reference="${prefix}tag_left_link">
      <visual>
        <material>
          <diffuse>1 1 1 1</diffuse>
          <specular>0 0 0 1</specular>
          <pbr>
            <metal>
              <albedo_map>file://$(find ros2_fra2mo)/models/arucotag_201/aruco-201.png</albedo_map>
            </metal>
          </pbr>
        </material>
      </visual>
    </gazebo>

    <link name="${prefix}tag_right_link">
      <visual> 
        <geometry> <box size="0.1 0.1 0.001"/> </geometry> 
        <material name="White"> <color rgba="1 1 1 1"/> </material> 
      </visual>
      <inertial> <mass value="0.00001"/> <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/> </inertial>
    </link>

    <joint name="${prefix}parcel_to_tag_right" type="fixed">
      <parent link="${prefix}parcel_link"/>
      <child link="${prefix}tag_right_link"/>
      <origin xyz="0 -0.101 0" rpy="1.5708 0 0"/> 
    </joint>

    <gazebo reference="${prefix}tag_right_link">
      <visual>
        <material>
          <diffuse>1 1 1 1</diffuse>
          <specular>0 0 0 1</specular>
          <pbr>
            <metal>
              <albedo_map>file://$(find ros2_fra2mo)/models/arucotag_201/aruco-201.png</albedo_map>
            </metal>
          </pbr>
        </material>
      </visual>
    </gazebo>

    <gazebo reference="${prefix}d435_link">
      <sensor name="fra2mo_camera" type="camera">
        <always_on>true</always_on>
        <update_rate>30.0</update_rate>
        <visualize>true</visualize>
        <topic>/fra2mo/camera/image</topic> 
        <camera name="fra2mo_head">
          <horizontal_fov>1.3962634</horizontal_fov>
          <image> <width>800</width> <height>800</height> <format>R8G8B8</format> </image>
          <clip> <near>0.02</near> <far>300</far> </clip>
        </camera>
      </sensor>
    </gazebo>

    <gazebo>
      <plugin name="ignition::gazebo::systems::DiffDrive" filename="libignition-gazebo-diff-drive-system.so">
        <left_joint>${prefix}left_wheel_joint</left_joint>
        <right_joint>${prefix}right_wheel_joint</right_joint>
        <wheel_separation>${wheel_axle}</wheel_separation>
        <wheel_radius>${wheel_radius}</wheel_radius>
        <odom_publish_frequency>50</odom_publish_frequency>
        <topic>/fra2mo/cmd_vel</topic>
      </plugin>
    </gazebo>

    <gazebo reference="${prefix}trailer_wheel_l">
      <mu1>1.0</mu1>
      <mu2>0.1</mu2> <kp>1000000.0</kp>
      <kd>1.0</kd>
    </gazebo>

    <gazebo reference="${prefix}trailer_wheel_r">
      <mu1>1.0</mu1>
      <mu2>0.1</mu2> <kp>1000000.0</kp>
      <kd>1.0</kd>
    </gazebo>

    <gazebo reference="${prefix}trailer_link">
      <mu1>0.1</mu1>
      <mu2>0.1</mu2>
    </gazebo>

  </xacro:macro>
</robot>